### ISSUE TITLE
Name change

### ISSUE THREAD

**Issue by apalchys** [apalchys/demand-for-money#4]
I consider to change repo name to make it more generic and remove reference to some company.

Possible options:
- `i-need-money`
- `open-source-ftw`

Does anybody have other ideas?

@MysterionRise

**Comment by MysterionRise** [comment]
@apalchys  what about `money-for-opensource` ?

**Comment by MysterionRise** [comment]
@apalchys what about `demand-for-money` ?

**Comment by apalchys** [comment]
> @apalchys what about `demand-for-money` ?

Done. Thank you!
